.\"                                      Hey, EMACS: -*- nroff -*-
.TH PENGUIN-COMMAND 6 "November 10, 2002"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
penguin-command \- a missile command clone
.SH SYNOPSIS
.B penguin-command
.RB [ \-\-fullscreen | \-f ]
.RB [ \-\-windowed | \-w ]
.RB [ \-\-nosound | \-s ]
.RB [ \-\-lefthandedmouse | \-l ]
.SH DESCRIPTION
This is a clone of the classic "Missile Command" Game, but it has better
graphics and music. You have to defend cities by shooting at missiles 
and smartbombs.
.SH OPTIONS
.TP
.B \-\-fullscreen, \-f
Run in fullscreen mode (default).
.TP
.B \-\-windowed, \-w
Run in windowed mode.
.TP
.B \-\-nosound, \-s
Run without sound.
.TP
.B \-\-lefthandedmouse, \-l
Swaps left and right mouse buttons.
.TP
.B \-\-help, \-h
Display help.
.SH AUTHOR
This manual page was written by Karl Bartel <karlb@gmx.net>.
