.\"                                      Hey, EMACS: -*- nroff -*-
.TH PENGUIN-COMMAND 6 "November 10, 2002"
.\" Please adjust this date whenever revising the manpage.
.SH 名前
penguin-command \- missile command のクローン
.SH 書式
.B penguin-command
.RB [ \-\-fullscreen | \-f ]
.RB [ \-\-windowed | \-w ]
.RB [ \-\-nosound | \-s ]
.RB [ \-\-lefthandedmouse | \-l ]
.SH 説明
懐かしの "Missile Command" ゲームのクローンですが、
サウンドとグラフィックが改良されています。
ミサイルやスマート爆弾を撃ち落とすことによって都市を守るゲームです。
.SH オプション
.TP
.B \-\-fullscreen, \-f
フルスクリーンモード(デフォルト)
.TP
.B \-\-windowed, \-w
ウィンドウモード
.TP
.B \-\-nosound, \-s
サウンド無し
.TP
.B \-\-lefthandedmouse, \-l
マウスの右ボタンと左ボタンを反転
.TP
.B \-\-help, \-h
へルプを表示
.SH AUTHOR
このマニュアルは
Karl Bartel <karlb@gmx.net>
によって書かれた。
